abbreviations = {
    "WIBTAH": "Would I be the butt hole",
    "WIBTA": "Would I be the butt hole",
    "AITAH": "Am I the butt hole",
    "AITA": "Am I the butt hole",
    "TL : DR": "TLDR",
    "TL:DR": "TLDR",
    "TL;DR": "TLDR",
    "TL; DR": "TLDR",
    "TL: DR": "TLDR",
    "TIFU": "Today I fricked up",
    "AH": "butt hole",
    "BIL": "brother in law",
    "MIL": "mother in law",
    "FIL": "father in law",
    "DIL": "daughter in law",
    "idk": "I don't know",
    "idrc": "I don't really care",
    "idc": "I don't care",
    "rn": "right now",
    "bc": "because",
    "btw": "by the way",
    "gf": "girlfriend",
    "bf": "boyfriend",
    "wtf": "what the fuck",
    "wth": "what the hell",
    "tbh": "to be honest",
    "ofc": "of course",
    "fucking": "freaking",
    "fuck": "frick",
    "shit": "poop",
    "shitting": "pooping",
    "Shit": "Poop",
    "cock": "chicken",
    "pussy": "bussy",
    "dead": "unalive",
    "killed": "unalived",
    "died": "unalived",
    "kill": "unalive",
    "asshole": "butthole",
    "ass": "butt",
}